// @enterprise-future — not wired to production

import { writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'
import type { ProviderChoices } from './profiles.js'
import type { Secrets } from './secrets.js'

export interface ProjectFiles {
  envLocal: string
  overlayConfig: string
  dockerCompose: string
}

function buildEnvLocal(choices: ProviderChoices, secrets: Secrets, custom: Record<string, string>): string {
  const lines: string[] = ['# Auto-generated by create-overlay-app — do not commit', '']

  // Database
  if (choices.database === 'postgres') {
    lines.push(`DATABASE_URL=postgres://overlay:${secrets.postgresPassword}@localhost:5432/overlay`)
  } else if (choices.database === 'convex') {
    lines.push(`NEXT_PUBLIC_CONVEX_URL=${custom.NEXT_PUBLIC_CONVEX_URL || ''}`)
    lines.push(`CONVEX_DEPLOY_KEY=${custom.CONVEX_DEPLOY_KEY || ''}`)
  }

  // Auth
  if (choices.auth === 'workos') {
    lines.push(`WORKOS_CLIENT_ID=${custom.WORKOS_CLIENT_ID || ''}`)
    lines.push(`WORKOS_API_KEY=${custom.WORKOS_API_KEY || ''}`)
  } else if (choices.auth === 'keycloak') {
    lines.push(`KEYCLOAK_URL=http://localhost:8080`)
    lines.push(`KEYCLOAK_REALM=overlay`)
    lines.push(`KEYCLOAK_CLIENT_ID=overlay-web`)
    lines.push(`KEYCLOAK_CLIENT_SECRET=${secrets.jwtSecret}`)
  }

  // AI
  if (choices.aiGateway === 'vercel-ai') {
    lines.push(`AI_GATEWAY_URL=${custom.AI_GATEWAY_URL || ''}`)
    lines.push(`AI_GATEWAY_KEY=${custom.AI_GATEWAY_KEY || ''}`)
  } else if (choices.aiGateway === 'ollama') {
    lines.push(`OLLAMA_BASE_URL=http://localhost:11434`)
  }

  // Storage
  if (choices.storage === 'r2') {
    lines.push(`R2_ENDPOINT=${custom.R2_ENDPOINT || ''}`)
    lines.push(`R2_ACCESS_KEY_ID=${custom.R2_ACCESS_KEY_ID || ''}`)
    lines.push(`R2_SECRET_ACCESS_KEY=${custom.R2_SECRET_ACCESS_KEY || ''}`)
    lines.push(`R2_BUCKET_NAME=${custom.R2_BUCKET_NAME || ''}`)
  } else if (choices.storage === 'minio') {
    lines.push(`MINIO_ENDPOINT=http://localhost:9000`)
    lines.push(`MINIO_ROOT_USER=${secrets.minioRootUser}`)
    lines.push(`MINIO_ROOT_PASSWORD=${secrets.minioRootPassword}`)
  }

  // Billing
  if (choices.billing === 'stripe') {
    lines.push(`STRIPE_SECRET_KEY=${custom.STRIPE_SECRET_KEY || ''}`)
    lines.push(`STRIPE_WEBHOOK_SECRET=${custom.STRIPE_WEBHOOK_SECRET || ''}`)
  }

  // Queue
  if (choices.queue === 'bullmq') {
    lines.push(`REDIS_URL=redis://localhost:6379`)
  }

  // Search
  if (choices.search === 'meilisearch') {
    lines.push(`MEILISEARCH_URL=http://localhost:7700`)
    lines.push(`MEILISEARCH_API_KEY=${secrets.meiliMasterKey}`)
  }

  // Secrets
  lines.push(`JWT_SECRET=${secrets.jwtSecret}`)
  lines.push(`COOKIE_SECRET=${secrets.cookieSecret}`)
  lines.push(`ENCRYPTION_KEY=${secrets.encryptionKey}`)

  lines.push('')
  return lines.join('\n')
}

function buildOverlayConfig(choices: ProviderChoices): string {
  const config = {
    version: '1.0',
    profile: 'on-prem',
    providers: choices,
    enterprise: {
      requireApprovalForSignUp: false,
      allowLocalAuth: true,
      enableAuditLog: true,
      maxUsers: 0,
      sessionDurationMinutes: 10080,
      customDomain: null,
    },
    plugins: {
      scanLocalDirectory: './plugins',
      autoEnable: false,
    },
  }
  return JSON.stringify(config, null, 2)
}

function buildDockerComposeOverride(choices: ProviderChoices): string {
  const services: string[] = []

  if (choices.database === 'postgres') {
    services.push(`  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: overlay
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: overlay
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U overlay"]
      interval: 5s
      timeout: 5s
      retries: 5`)
  }

  if (choices.queue === 'bullmq') {
    services.push(`  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data`)
  }

  if (choices.storage === 'minio') {
    services.push(`  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: \${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: \${MINIO_ROOT_PASSWORD}
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000"
      - "9001:9001"`)
  }

  if (choices.search === 'meilisearch') {
    services.push(`  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      MEILI_MASTER_KEY: \${MEILI_MASTER_KEY}
    volumes:
      - meilisearchdata:/meili_data
    ports:
      - "7700:7700"`)
  }

  const volumes: string[] = []
  if (choices.database === 'postgres') volumes.push('  pgdata:')
  if (choices.queue === 'bullmq') volumes.push('  redisdata:')
  if (choices.storage === 'minio') volumes.push('  miniodata:')
  if (choices.search === 'meilisearch') volumes.push('  meilisearchdata:')

  const lines = ['# Auto-generated by create-overlay-app', 'services:']
  for (const s of services) lines.push(s)
  if (volumes.length > 0) {
    lines.push('')
    lines.push('volumes:')
    for (const v of volumes) lines.push(v)
  }
  return lines.join('\n')
}

export function writeProjectFiles(
  dir: string,
  choices: ProviderChoices,
  secrets: Secrets,
  customEnv: Record<string, string>
): ProjectFiles {
  const dockerDir = join(dir, 'docker')
  mkdirSync(dockerDir, { recursive: true })

  const envLocal = buildEnvLocal(choices, secrets, customEnv)
  const overlayConfig = buildOverlayConfig(choices)
  const dockerCompose = buildDockerComposeOverride(choices)

  writeFileSync(join(dir, '.env.local'), envLocal)
  writeFileSync(join(dir, 'overlay.config.json'), overlayConfig)
  writeFileSync(join(dockerDir, 'docker-compose.enterprise.yml'), dockerCompose)

  return { envLocal, overlayConfig, dockerCompose }
}
