import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const SOURCE_URL = 'https://ai-gateway.vercel.sh/v1/models'
const OUTPUT_PATH = path.join(process.cwd(), 'src/lib/generated/vercel-ai-gateway-pricing.ts')

type GatewayModelResponse = {
  id: string
  name?: string
  type?: string
  context_window?: number
  max_tokens?: number
  tags?: string[]
  pricing?: Record<string, unknown>
}

function sortRecord(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortRecord)
  if (!value || typeof value !== 'object') return value
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, entry]) => [key, sortRecord(entry)]),
  )
}

async function main() {
  const response = await fetch(SOURCE_URL, { cache: 'no-store' })
  if (!response.ok) {
    throw new Error(`Vercel AI Gateway pricing sync failed: ${response.status} ${response.statusText}`)
  }

  const payload = (await response.json()) as { data?: GatewayModelResponse[] }
  const models = Array.isArray(payload.data) ? payload.data : []
  if (models.length === 0) {
    throw new Error('Vercel AI Gateway pricing sync returned no models')
  }

  const snapshotModels = Object.fromEntries(
    models
      .filter((model) => model.id && model.pricing)
      .sort((a, b) => a.id.localeCompare(b.id))
      .map((model) => [
        model.id,
        {
          id: model.id,
          name: model.name ?? model.id,
          type: model.type ?? 'unknown',
          contextWindow: model.context_window ?? null,
          maxTokens: model.max_tokens ?? null,
          tags: [...(model.tags ?? [])].sort(),
          pricing: sortRecord(model.pricing ?? {}),
        },
      ]),
  )

  const snapshot = {
    generatedAt: new Date().toISOString(),
    source: SOURCE_URL,
    models: snapshotModels,
  }

  const contents = [
    '// Generated by `npm run pricing:sync`. Do not edit manually.',
    '',
    `export const VERCEL_AI_GATEWAY_PRICING_SNAPSHOT = ${JSON.stringify(snapshot, null, 2)} as const`,
    '',
  ].join('\n')

  await mkdir(path.dirname(OUTPUT_PATH), { recursive: true })
  await writeFile(OUTPUT_PATH, contents, 'utf8')
  console.log(`Wrote ${Object.keys(snapshotModels).length} priced model rows to ${OUTPUT_PATH}`)
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
