import { defineOverlayExtension } from '@overlay/extension-sdk'

export const jpisSchoolExtension = defineOverlayExtension({
  id: 'jpis-school',
  version: '1.0.0',
  navigation: [
    {
      id: 'student-dashboard',
      label: 'Student',
      href: '/app/x/student',
      icon: 'sparkles',
      componentKey: 'school.modules.studentDashboard',
    },
    {
      id: 'teacher-dashboard',
      label: 'Teacher',
      href: '/app/x/teacher',
      icon: 'user',
      componentKey: 'school.modules.teacherDashboard',
    },
    {
      id: 'parent-dashboard',
      label: 'Parent',
      href: '/app/x/parent',
      icon: 'mail',
      componentKey: 'school.modules.parentDashboard',
    },
    {
      id: 'admin-dashboard',
      label: 'Admin',
      href: '/app/x/admin',
      icon: 'shield-check',
      componentKey: 'school.modules.adminDashboard',
    },
  ],
  featureModules: [
    {
      id: 'student-dashboard',
      label: 'Student',
      description: 'Student dashboard for JPIS IB and Cambridge IGCSE learning workflows.',
      navigationItemId: 'student-dashboard',
      routePatterns: ['/app/x/student'],
      componentKey: 'school.modules.studentDashboard',
      packageName: 'src/extensions/jpis-school',
      order: 80,
    },
    {
      id: 'teacher-dashboard',
      label: 'Teacher',
      description: 'Teacher dashboard for JPIS IB and Cambridge IGCSE classroom operations.',
      navigationItemId: 'teacher-dashboard',
      routePatterns: ['/app/x/teacher'],
      componentKey: 'school.modules.teacherDashboard',
      packageName: 'src/extensions/jpis-school',
      order: 81,
    },
    {
      id: 'parent-dashboard',
      label: 'Parent',
      description: 'Parent-safe JPIS progress dashboard across IB and Cambridge IGCSE pathways.',
      navigationItemId: 'parent-dashboard',
      routePatterns: ['/app/x/parent'],
      componentKey: 'school.modules.parentDashboard',
      packageName: 'src/extensions/jpis-school',
      order: 82,
    },
    {
      id: 'admin-dashboard',
      label: 'Admin',
      description: 'Admin dashboard for JPIS curriculum operations, compliance, and AI rollout governance.',
      navigationItemId: 'admin-dashboard',
      routePatterns: ['/app/x/admin'],
      componentKey: 'school.modules.adminDashboard',
      packageName: 'src/extensions/jpis-school',
      order: 83,
    },
  ],
  policyGates: [
    {
      id: 'school-dashboards',
      label: 'School Dashboards',
      description: 'Controls access to student, teacher, parent, and admin extension dashboards.',
      defaultEnabled: true,
      enforcement: 'disable',
    },
  ],
})
